import type { CompressionCore, CompressionInput } from "@/lib/compression";

function safeProjectName(projectName: string) {
  return projectName.trim() || "Untitled project";
}

export function buildHandoffMarkdown(
  input: CompressionInput,
  result: CompressionCore,
) {
  const projectName = safeProjectName(input.projectName);

  return `# ${projectName} Handoff

## Source
- Tool: ${input.sourceTool}
- Generated by: 맥락 보라돌이 MVP mock compression

## 세션 요약
${result.sessionSummary}

## 확정된 결정사항
${result.confirmedDecisions}

## 제안되었지만 확정되지 않은 내용
${result.proposedIdeas}

## 열린 질문
${result.openQuestions}

## 다음 액션
${result.nextActions}

## Safety
- Do not paste API keys, passwords, tokens, private URLs, or private financial data into public repos.
- This MVP result was generated locally without calling an external AI API.
`;
}

export function buildAgentsMd(input: CompressionInput, result: CompressionCore) {
  const projectName = safeProjectName(input.projectName);

  return `# AGENTS.md

## Project
${projectName}

## Context Source
Imported from ${input.sourceTool} through 맥락 보라돌이.

## Working Rules
- Do not invent decisions.
- Separate confirmed decisions from ideas.
- Never store secrets, API keys, credentials, tokens, private URLs, or private financial information.
- Prefer small, reviewable changes.

## Confirmed Decisions
${result.confirmedDecisions}

## Open Questions
${result.openQuestions}

## Next Actions
${result.nextActions}
`;
}

export function buildClaudeMd(input: CompressionInput, result: CompressionCore) {
  return `@AGENTS.md

## Claude Code Notes
Use this handoff as the latest shared project context.

## Session Summary
${result.sessionSummary}

## Next Actions
${result.nextActions}
`;
}

export function buildGeminiMd(input: CompressionInput, result: CompressionCore) {
  return `# GEMINI.md

@./AGENTS.md

## Gemini CLI Notes
Use this project's handoff as the canonical context imported from ${input.sourceTool}.

## Open Questions
${result.openQuestions}

## Next Actions
${result.nextActions}
`;
}

export function downloadMarkdownFile(filename: string, contents: string) {
  if (typeof window === "undefined") {
    return;
  }

  const blob = new Blob([contents], {
    type: "text/markdown;charset=utf-8",
  });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}
