type MarkdownInput = {
  projectName: string;
  sourceTool: string;
  targetTool?: string;
  sourceCount?: number;
  mode?: "single" | "merged";
};

type MarkdownCore = {
  northStar: string;
  sessionSummary: string;
  confirmedDecisions: string;
  proposedIdeas: string;
  openQuestions: string;
  nextActions: string;
};

function safeProjectName(projectName: string) {
  return projectName.trim() || "Untitled project";
}

function buildSourceBlock(input: MarkdownInput) {
  const sourceLabel =
    input.mode === "merged"
      ? `${input.sourceCount ?? 0} collected context pieces`
      : input.sourceTool;

  const targetLine = input.targetTool
    ? `- Target tool: ${input.targetTool}\n`
    : "";

  return `- Source: ${sourceLabel}
${targetLine}- Generated by: 맥락 보라돌이 MVP mock compression`;
}

export function buildHandoffMarkdown(
  input: MarkdownInput,
  result: MarkdownCore,
) {
  const projectName = safeProjectName(input.projectName);

  return `# ${projectName} Handoff

## Source
${buildSourceBlock(input)}

## 북극성
${result.northStar}

## 세션 요약
${result.sessionSummary}

## 확정된 결정사항
${result.confirmedDecisions}

## 제안되었지만 확정되지 않은 내용
${result.proposedIdeas}

## 열린 질문
${result.openQuestions}

## 다음 액션
${result.nextActions}

## Safety
- Do not paste API keys, passwords, tokens, private URLs, or private financial data into public repos.
- This MVP result was generated locally without calling an external AI API.
`;
}

export function buildAgentsMd(input: MarkdownInput, result: MarkdownCore) {
  const projectName = safeProjectName(input.projectName);
  const targetLine = input.targetTool
    ? `\n## Target Tool\n${input.targetTool}\n`
    : "";

  return `# AGENTS.md

## Project
${projectName}

## Context Source
Imported from ${input.sourceTool} through 맥락 보라돌이.
${targetLine}

## Working Rules
- Do not invent decisions.
- Separate confirmed decisions from ideas.
- Never store secrets, API keys, credentials, tokens, private URLs, or private financial information.
- Prefer small, reviewable changes.
- Keep the north star visible when choosing the next action.

## North Star
${result.northStar}

## Confirmed Decisions
${result.confirmedDecisions}

## Open Questions
${result.openQuestions}

## Next Actions
${result.nextActions}
`;
}

export function buildClaudeMd(input: MarkdownInput, result: MarkdownCore) {
  return `@AGENTS.md

## Claude Code Notes
Use this handoff as the latest shared project context${
    input.targetTool ? ` for ${input.targetTool}` : ""
  }.

## North Star
${result.northStar}

## Session Summary
${result.sessionSummary}

## Next Actions
${result.nextActions}
`;
}

export function buildGeminiMd(input: MarkdownInput, result: MarkdownCore) {
  return `# GEMINI.md

@./AGENTS.md

## Gemini CLI Notes
Use this project's handoff as the canonical context imported from ${input.sourceTool}${
    input.targetTool ? ` for ${input.targetTool}` : ""
  }.

## North Star
${result.northStar}

## Open Questions
${result.openQuestions}

## Next Actions
${result.nextActions}
`;
}

export function downloadMarkdownFile(filename: string, contents: string) {
  if (typeof window === "undefined") {
    return;
  }

  const blob = new Blob([contents], {
    type: "text/markdown;charset=utf-8",
  });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  window.URL.revokeObjectURL(url);
}
